/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Pipe({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('models/pipe_3.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.pipe_big_3.geometry} material={materials.pipe_big_3} position={[0.01, 0.85, -0.03]} rotation={[Math.PI / 2, 0, 0]} scale={0.11} />
    </group>
  )
}

useGLTF.preload('models/pipe_3.glb')
